DELIMITER $
CREATE TRIGGER TRG_DELETE_ALUNO BEFORE DELETE ON TBL_ALUNO

for each row 
BEGIN
INSERT INTO TBL_ALUNO_BKP
SET
ID_ALUNO = OLD.ID_ALUNO,
ID_TURMA = OLD.ID_TURMA,
NOME = OLD.NOME,
CPF = OLD.CPF,
RG = OLD.RG,
TELEFONE_ALUNO = OLD.TELEFONE_ALUNO,
TELEFONE_RESPONSAVEL = OLD.TELEFONE_RESPONSAVEL,
EMAIL = OLD.EMAIL,
DATA_NASCIMENTO = OLD.DATA_NASCIMENTO;
END;
$
